###
POST http://localhost:3000/api/addauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Virginia Woolf",
    "countryAuthor": "Inglatera",
    "yearBornAuthor": 1882
}

###
GET http://localhost:3000/api/getallauthors HTTP/1.1

###
GET http://localhost:3000/api/getauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Sara Mesa"
}

###
GET http://localhost:3000/api/getonebookbyauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Sara Mesa",
    "titleBook": "Cicatriz"
}

###
GET http://localhost:3000/api/getallbooksbyauthor HTTP/1.1
Content-Type: application/json

{

}


###
POST http://localhost:3000/api/addbook HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Paul Benjamin Auster",
    "titleBook": "Mr. Vértigo",
    "yearBook": 1994,
    "pagesBook": 216
}

###
DELETE  http://localhost:3000/api/deletebook HTTP/1.1
Content-Type: application/json

{
    "titleBook": "Mr. Vértigo"
}

###
DELETE  http://localhost:3000/api/deleteauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Miguel de Cervantes Saavedra"
}

###
PATCH http://localhost:3000/api/updatebook HTTP/1.1
Content-Type: application/json

{
    "titleBook": "El cuaderno rojo",
    "yearBook": 1993,
    "pagesBook": 46
}

###
PATCH http://localhost:3000/api/updateauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Henry Miller",
    "countryAuthor": "Estados Unidos",
    "yearBornAuthor": 1899
}