###
POST http://localhost:3000/api/addauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Virginia Woolf",
    "countryAuthor": "Inglatera",
    "yearBornAuthor": 1882
}

###
GET http://localhost:3000/api/getallauthors HTTP/1.1

###
GET http://localhost:3000/api/getauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Sara Mesa"
}

###
GET http://localhost:3000/api/getonebookbyauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Sara Mesa",
    "titleBook": "Cicatriz"
}

###
GET http://localhost:3000/api/getallbooksbyauthor HTTP/1.1
Content-Type: application/json

{

}


###
POST http://localhost:3000/api/addbook HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Sara Mesa",
    "titleBook": "Un Amor",
    "yearBook": 2020,
    "pagesBook": 192
}

