###
POST http://localhost:3000/api/addauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Haruki Murakami",
    "countryAuthor": "Japon",
    "yearBornAuthor": 1949
}

###
POST http://localhost:3000/api/addauthor HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Sara Mesa",
    "countryAuthor": "España",
    "yearBornAuthor": 1976
}

###
GET http://localhost:3000/api/getallauthors HTTP/1.1

###
GET http://localhost:3000/api/getauthor HTTP/1.1


###
POST http://localhost:3000/api/addbook HTTP/1.1
Content-Type: application/json

{
    "nameAuthor": "Ernest Hemingway",
    "titleBook": "Adios a las armas",
    "yearBook": 1929,
    "pagesBook": 376
}

